# Если вы добавили новый плагин вам надо написать его имя в этом файле, чтоб скрип смог автоматически добавть ваш плагин 
# в автообновления. Важно чтоб названия плагина было таким же как названия репозитория и плагина который вы добавили!!!
# Имя плагина добавлять через пробел строго в одну строку в конце строки "plugins".
plugins: 
